Lambda-School-Labs/family-promise-service-tracker-fe-b

- src/components/common/Navbar/HamburgerMenu.js
- src/components/pages/Login/LoginContainer.js
- Fixed Navigation where on 'back button' click the navigation bar would stay visible -- NOW on 'back button' press, you are kept at the home page if logged in. In order to log out now, you need to hit the 'Log Out' button.
- Fixed a bug where the 'role' in local storage wasn't clearing on log-out.
• For the 'Bugs' User Story/Tab in Trello
Bug Fix and New Feature 
#Change Status
[x] Yes
[x] My code has been reviewed by at least one peer
[x] I have commented my code, particularly in hard-to-understand areas
[x] I have made corresponding changes to the documentation
[x] My changes generate no new warnings
[x] There are no …
> fixes navigation bug and role not getting removed

- src/components/forms/AddRecipientForm.js
- src/components/pages/Recipients/RenderRecipientsPage.js
I made a recipient form with the information that was talked about. I also connected the form to the recipient page
We needed to make a form in order to add a new Recipient to the data base. Also the add employee was in the spot of the use recipient button so that needed to be changed
As a service worker I can manage recipients
[X] New feature (non-breaking change which adds functionality)
Change Status
[X] Completed, ready to review and merge
[] Yes
[X] My code follows the style guidelines of this project
[X] I have performed a self-review of my own code
[] My code has been reviewed by …
> This gives a recipient form and connects it to the recipient page

- src/components/common/Navbar/HamburgerMenu.js
- src/components/pages/Login/LoginContainer.js
- src/index.js
Reverts Lambda-School-Labs/family-promise-service-tracker-fe-b#4
> Revert "Fixes navigation bar disappearing and appearing bug"

- src/components/common/Navbar/NavbarHeader.js
- src/components/common/Title.js
- src/components/pages/MyProfile/MyProfileContainer.js
- src/components/pages/MyProfile/RenderMyProfile.js
- src/styles/Employees.scss
- src/styles/Layout.scss
- src/styles/Profile.scss
- src/styles/Programs.scss
- src/styles/Services.scss
- src/styles/commonComponents.scss
- Added responsiveness to multiple desktop screen sizes
- Added remaining breakpoints for 991px tablet width size
- Changed many REM measurements to percentages for better response to window size change.
- Better design will result in a better UX. Horizontal scrolling will be prevented by these changes.
- As a user, I should have a good UX/UI experience.
Change Status
[x] Yes …
> Adds responsive design to elements and breakpoints for tablet use

- src/components/forms/AddServiceTypeForm.js
I created a form so a program manager could add services to any program they are involved with
This form was needed so program managers could add services to their programs to the database
As a program manager I can add services to any program I am involved with
https://gyazo.com/c4a06219f182625fea08c1f4ee26361a
https://gyazo.com/145bc42521c4255c868a79c24ef593b2
Change Status
[x] Yes
[x] I have performed a …
> added new service type form to addedservicetypeform.js

- src/components/common/ServicesTable/ServiceTable.js
- src/components/pages/Services/RenderServicesPage.js
- src/components/pages/Services/ServicesContainer.js
- src/state/actions/ServiceTypeActions.js
- src/state/actions/index.js
- src/state/reducers/serviceTypeReducer.js
- Services table was added pulling from the backend. Waiting on new backend to get endpoints working so the table can be fine-tuned to the new data set.
- Originally the services table was pulling from programs and was using the same component. Now services has its own table component and data.
- As an Admin I can create, edit, and delete services
- 
Change Status
[x] Yes
[] My …
> Adds new services table, that's waiting for the new backend to be wired properly

- src/components/forms/AddRecipientForm.js
Finalized the AddRecipient form adds all the states and adds ethnicity fields
We needed to get all the states added and needed to make sure all data fields required by the back end were there
as a service manager I can add recipients
[X] New feature (non-breaking change which adds functionality)
Change Status
[] Yes
[X] My code follows the style guidelines of this project
[]X I have performed a self-review of my own code
[X] I have commented my code, particularly in …
> Adds all the states and the ethnicity feild

- src/components/common/ServicesTable/ServiceTable.js
- src/components/forms/AddServiceTypeForm.js
changed the input fields in add service type to include much less data and changed the table to include the data from the form
I changed the service type form to include much less data than what was needed and reflected that data to the table.
This was done to give program managers the list of service types that are available
https://gyazo.com/0c5a315ca6ace32ceb6cbbd8a08818c8
https://gyazo.com/515a477b44a6b55b36679f01df1f5c0d
Change Status
[x] Yes
[x] My code …
> Changed service type form and fixed services table to include data from form

- src/components/pages/MyProfile/RenderMyProfile.js
- src/utils/axiosWithAuth.js
- The programs feature wasn't functional and was throwing errors on login. This fixes that issue and brings back the old functionality of showing programs.
- To provide a clear user experience and bring back functionality that we had lost.
- My Profile renders properly
Change Status
[x] Yes
[x] I have commented my code, particularly in hard-to-understand areas
[x] I have made …
> adds program functionality back to myProfile

- src/components/common/ServicesTable/ServiceTable.js
- src/state/actions/ServiceTypeActions.js
added program ID to service table and got the editing and delete functional
we had an empty bit for the program type and we couldn't edit or delete service types
Change Status
[] Yes
[] My …
> getting edit and delete working on service type

- src/components/pages/AdminDash/AdminDashContainer.js
- src/components/pages/ProgramsDash/ProgramsDashContainer.js
- src/components/pages/RoutingPage/index.js
- src/components/pages/ServicesDash/ServicesDashContainer.js
- src/index.js
- src/state/reducers/userReducer.js
upon logging in, user is now routed to the correct dashboard based upon the users' credentials.
added a "RoutingPage" to do a check on the users' credentials and then route to the correct dashboard.
upon logging in, the user was still being routed to the profile page. This PR fixes that issue and routes to a dashboard instead.
Change Status
[x] Yes
[x] I have commented my code, particularly in hard-to-understand …
> added functionality to dynamically route the user to the correct dashboard upon logging in

- src/components/common/Navbar/HamburgerMenu.js
- src/components/pages/MyProfile/MyProfileContainer.js
- src/components/pages/MyProfile/RenderMyProfile.js
- src/components/pages/Programs/RenderProgramsPage.js
- src/components/pages/RoutingPage/index.js
- src/components/pages/Services/RenderServicesPage.js
- src/index.js
- src/state/actions/ServiceTypeActions.js
profile in the nav bar now routes to the users profile correctly
added code to route to each users profile correctly
users still need a way to get to their own profile in order to edit it
Change Status
[x] Yes
[x] My code has been reviewed by at least one peer
[x] I have commented my code, particularly in hard-to-understand areas
[x] My changes generate no new warnings
[x] There are no merge conflicts
> profile in the nav bar now routes to the users profile correctly

- src/components/pages/MyProfile/RenderMyProfile.js
Added styling to the MyProfile page to make it look cleaner
In order to make the my profile page less of an eye sore
Change Status
[x] Yes
[x] My code has been reviewed by at least one peer
[x] My changes generate no new warnings
[x] …
> styled the myprofile page to look cleaner

- src/components/common/ServicesTable/ServiceTable.js
Added back service type name and program it was associated with
in order to display correct data
Change Status
[] Yes
[] My changes generate no new warnings
[] There are no merge conflicts
> got name and program to display

- src/components/common/Navbar/HamburgerMenu.js
Added Dashboard to the hamburger menu
That way each user can access their dashboard dependent on their role
https://gyazo.com/1c978c6bfa18908bceba9236c5ac28d9
Change Status
[] Yes
[x] …
> added Dashboard to hamburgermenu

- src/components/forms/AddServiceTypeForm.js
changes input form names in order to add services
so we can add services
Change Status
[] Yes
[] My changes generate no new warnings
[] There are no merge conflicts
> changes names for inputs

- src/components/pages/AdminDash/AdminDashContainer.js
- src/components/pages/ProgramsDash/ProgramsDashContainer.js
- src/components/pages/ServicesDash/ServicesDashContainer.js
Added static map images to the dashboards to simulate what it might look like when an actual Google Maps API is implemented.
Wrote some basic code to add images to the dashboards as a proof of concept
To have something to show that is closer to what the final product may look like
Change Status
[x] Yes …
> adds static map images to the dashboards to simulate what it might look like when actual Google API is implemented

- docs/KnownDefects.md
added feature type bug to known defect
so they would know about it
Change Status
[] Yes
[] My changes generate no new warnings
[] There are no merge conflicts
> Adds service table defect

- docs/KnownDefects.md
added the nav bar defect to the docs
left detailed information on the known defect for the next team
To let the other team know the defect that we found but did not have time to finish fixing. This saves them time because they won't have to go searching for the defect themselves.
> added the nav bar defect to the docs

- docs/labs-34-about.md
changed labs 33 to labs 34
because we are labs 34
Change Status
[] Yes
[] My changes generate no new warnings
[] There are no merge conflicts
> Changed from 33 to 34
